/**
 * Row shapes for the public schema.
 *
 * These are written by hand rather than produced by `supabase gen types`,
 * because generating them needs a running project and there is not one yet.
 * That would normally be a liability — hand-written types drift from the
 * schema silently — so `schema.contract.test.ts` boots the real migrations and
 * asserts every table, column and nullability here matches. Drift fails CI.
 *
 * When the Supabase project exists, `pnpm --filter @trinity-nexus/db db:types`
 * replaces this file and the contract test keeps guarding it.
 */

export type AppRole = 'member' | 'moderator' | 'admin';
export type ReactionKind = 'like' | 'helpful' | 'insightful' | 'celebrate';
export type NotificationKind = 'reply' | 'mention' | 'reaction' | 'moderation';
export type ReportStatus = 'open' | 'resolved' | 'dismissed';
export type ModerationActionKind =
  | 'delete_post'
  | 'restore_post'
  | 'lock_topic'
  | 'unlock_topic'
  | 'pin_topic'
  | 'unpin_topic'
  | 'move_topic'
  | 'ban_user'
  | 'unban_user';

/** Postgres `timestamptz`, serialised by PostgREST as an ISO 8601 string. */
export type Timestamp = string;
export type Uuid = string;

export interface GameRow {
  id: Uuid;
  slug: string;
  name: string;
  sort_order: number;
  created_at: Timestamp;
}

export interface CategoryRow {
  id: Uuid;
  game_id: Uuid;
  slug: string;
  name: string;
  description: string | null;
  sort_order: number;
  allow_anonymous: boolean;
  is_locked: boolean;
  created_at: Timestamp;
}

export interface ProfileRow {
  id: Uuid;
  username: string;
  display_name: string;
  avatar_url: string | null;
  bio: string | null;
  role: AppRole;
  banned_until: Timestamp | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export interface TopicRow {
  id: Uuid;
  category_id: Uuid;
  /** Null once the author deletes their account; the topic survives them. */
  author_id: Uuid | null;
  title: string;
  slug: string;
  is_pinned: boolean;
  is_locked: boolean;
  reply_count: number;
  last_activity_at: Timestamp;
  created_at: Timestamp;
  updated_at: Timestamp;
  deleted_at: Timestamp | null;
  /** Generated by Postgres; never written by the client. */
  search_vector: string | null;
}

export interface PostRow {
  id: Uuid;
  topic_id: Uuid;
  author_id: Uuid | null;
  parent_id: Uuid | null;
  body_md: string;
  /** Ancestry from the root down to and including this post. */
  path: Uuid[];
  depth: number;
  is_opening_post: boolean;
  edited_at: Timestamp | null;
  created_at: Timestamp;
  deleted_at: Timestamp | null;
  search_vector: string | null;
}

export interface TagRow {
  id: Uuid;
  slug: string;
  name: string;
  created_at: Timestamp;
}

export interface TopicTagRow {
  topic_id: Uuid;
  tag_id: Uuid;
}

export interface ReactionRow {
  post_id: Uuid;
  profile_id: Uuid;
  kind: ReactionKind;
  created_at: Timestamp;
}

export interface MentionRow {
  post_id: Uuid;
  profile_id: Uuid;
  created_at: Timestamp;
}

export interface SubscriptionRow {
  profile_id: Uuid;
  topic_id: Uuid | null;
  category_id: Uuid | null;
  created_at: Timestamp;
}

export interface NotificationRow {
  id: Uuid;
  recipient_id: Uuid;
  actor_id: Uuid | null;
  kind: NotificationKind;
  topic_id: Uuid | null;
  post_id: Uuid | null;
  read_at: Timestamp | null;
  created_at: Timestamp;
}

export interface ReportRow {
  id: Uuid;
  post_id: Uuid;
  reporter_id: Uuid;
  reason: string;
  status: ReportStatus;
  resolved_by: Uuid | null;
  resolved_at: Timestamp | null;
  created_at: Timestamp;
}

export interface ModerationActionRow {
  id: Uuid;
  moderator_id: Uuid | null;
  kind: ModerationActionKind;
  topic_id: Uuid | null;
  post_id: Uuid | null;
  target_profile_id: Uuid | null;
  note: string | null;
  created_at: Timestamp;
}

/**
 * The same information as the interfaces above, as data.
 *
 * The contract test compares this against `information_schema`; the interfaces
 * are what the application uses. Keeping both means the check is real — a
 * comparison derived from the types themselves could only ever agree with
 * itself.
 */
export const SCHEMA_CONTRACT = {
  games: { id: false, slug: false, name: false, sort_order: false, created_at: false },
  categories: {
    id: false,
    game_id: false,
    slug: false,
    name: false,
    description: true,
    sort_order: false,
    allow_anonymous: false,
    is_locked: false,
    created_at: false,
  },
  profiles: {
    id: false,
    username: false,
    display_name: false,
    avatar_url: true,
    bio: true,
    role: false,
    banned_until: true,
    created_at: false,
    updated_at: false,
  },
  topics: {
    id: false,
    category_id: false,
    author_id: true,
    title: false,
    slug: false,
    is_pinned: false,
    is_locked: false,
    reply_count: false,
    last_activity_at: false,
    created_at: false,
    updated_at: false,
    deleted_at: true,
    search_vector: true,
  },
  posts: {
    id: false,
    topic_id: false,
    author_id: true,
    parent_id: true,
    body_md: false,
    path: false,
    depth: false,
    is_opening_post: false,
    edited_at: true,
    created_at: false,
    deleted_at: true,
    search_vector: true,
  },
  tags: { id: false, slug: false, name: false, created_at: false },
  topic_tags: { topic_id: false, tag_id: false },
  reactions: { post_id: false, profile_id: false, kind: false, created_at: false },
  mentions: { post_id: false, profile_id: false, created_at: false },
  subscriptions: { profile_id: false, topic_id: true, category_id: true, created_at: false },
  notifications: {
    id: false,
    recipient_id: false,
    actor_id: true,
    kind: false,
    topic_id: true,
    post_id: true,
    read_at: true,
    created_at: false,
  },
  reports: {
    id: false,
    post_id: false,
    reporter_id: false,
    reason: false,
    status: false,
    resolved_by: true,
    resolved_at: true,
    created_at: false,
  },
  moderation_actions: {
    id: false,
    moderator_id: true,
    kind: false,
    topic_id: true,
    post_id: true,
    target_profile_id: true,
    note: true,
    created_at: false,
  },
} as const satisfies Record<string, Record<string, boolean>>;

export type TableName = keyof typeof SCHEMA_CONTRACT;
